# Generated by Django 4.1.3 on 2022-11-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_vagas_email_alter_vagas_nivel_experiencia"),
        ("vagas", "0002_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emails",
            name="vaga",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="empresa.vagas",
            ),
        ),
    ]
